export const GET_PRACTICES = 'GET_PRACTICES'
export const GET_PRACTICES_SUCCEED = 'GET_PRACTICES_SUCCEED'
export const DELETE_PRACTICE = 'DELETE_PRACTICE'
export const DELETE_PRACTICE_SUCCEED = 'DELETE_PRACTICE_SUCCEED'
export const UPDATE_PRACTICE = 'UPDATE_PRACTICE'
export const UPDATE_PRACTICE_SUCCEED = 'UPDATE_PRACTICE_SUCCEED'
export const ADD_PRACTICE = 'ADD_PRACTICE'
export const ADD_PRACTICE_SUCCEED = 'ADD_PRACTICE_SUCCEED'
export const GET_PRACTICE_BY_USER_ID = 'GET_PRACTICE_BY_USER_ID'
export const GET_PRACTICE_BY_USER_ID_SUCCEED = 'GET_PRACTICE_BY_USER_ID_SUCCEED'
export const CREATE_PRACTICE_LOCATION = 'CREATE_PRACTICE_LOCATION'
export const CREATE_PRACTICE_LOCATION_SUCCEED = 'CREATE_PRACTICE_LOCATION_SUCCEED'
export const UPDATE_PRACTICE_LOCATION = 'UPDATE_PRACTICE_LOCATION'
export const UPDATE_PRACTICE_LOCATION_SUCCEED = 'UPDATE_PRACTICE_LOCATION_SUCCEED'



