export default {
    host: 'http://localhost:8080/',
    authorize: 'dormitory-service/v1/authentication/authorize',
    studentProfile: 'dormitory-service/v1/user/findByLogin/',
    studentProfileById: 'dormitory-service/v1/user/',
    studentProfileByLogin: 'dormitory-service/v1/user/login/',
    updateStudentProfile: 'dormitory-service/v1/user/',
    updateDormitory: 'dormitory-service/v1/dormitory',
    getOccupancyDataByLogin: 'dormitory-service/v1/occupancies/active/userLogin/',
    getAllOccupanciesByLogin: 'dormitory-service/v1/occupancies/userLogin/',
    requestToChangePassword: 'dormitory-service/v1/user/changePasswordRequest/',
    changePassword: 'dormitory-service/v1/user/changePassword',
    getAllOccupancies: 'dormitory-service/v1/occupancies',
    getAllDormitories: 'dormitory-service/v1/dormitory',
    getReprimandsById: 'dormitory-service/v1/reprimands/userId/',
    deleteReprimandById: 'dormitory-service/v1/reprimands/',
    getDormitoryByNumber: 'dormitory-service/v1/dormitory/number/',
    getStudentDebtsById: 'dormitory-service/v1/payments/totalDebts/',
    addStudentToRoom: 'dormitory-service/v1/occupancies',
    createReprimand: 'dormitory-service/v1/reprimands',
    addRoomToDormitory: 'dormitory-service/v1/dormitory/',
    addDormitory: 'dormitory-service/v1/dormitory',
    deleteRoomFromDormitory: 'dormitory-service/v1/room/changeStatus/',
    deleteStudent: 'dormitory-service/v1/user/',
    deleteStudentFromRoom: 'dormitory-service/v1/occupancies/',
    deleteDormitory: 'dormitory-service/v1/dormitory/',
    payment: 'dormitory-service/v1/payments/userId/',
    uploadReceipt: 'dormitory-service/v1/payments/',
    declinePayment: 'dormitory-service/v1/payments/decline/',
    approvePayment: 'dormitory-service/v1/payments/approve/',
    getAllUsers: 'dormitory-service/v1/user',
    getDormitoryById: 'dormitory-service/v1/dormitory/',
    registerUser: 'dormitory-service/v1/user/registration?role=',
}

export const roles = {
    student: 'ROLE_STUDENT',
    accountant: 'ROLE_ACCOUNTANT',
    administrator: 'ROLE_ADMINISTRATOR',
    dean: 'ROLE_DEAN'
}
