export const AUTHORIZATION = 'AUTHORIZATION'
export const LOG_OUT = 'LOG_OUT'
export const AUTHORIZATION_SUCCEED = 'AUTHORIZATION_SUCCEED'
export const ADMIN = 'ADMIN'
export const PRACTICE_LEADER = 'PRACTICE_LEADER'
export const STUDENT = 'STUDENT'
export const HEAD_OF_DEPARTMENT = 'HEAD_OF_DEPARTMENT'

