export const CLEAR_ALERT_MESSAGE_SUCCEED = 'CLEAR_ALERT_MESSAGE_SUCCEED'
export const SET_ALERT_MESSAGE_SUCCEED = 'SET_ALERT_MESSAGE_SUCCEED'
export const LOADING_START_SUCCEED = 'LOADING_START_SUCCEED'
export const LOADING_END_SUCCEED = 'LOADING_END_SUCCEED'
