export const CREATE_USER = 'CREATE_USER'
export const CREATE_USER_SUCCEED = 'CREATE_USER_SUCCEED'
export const EDIT_USER = 'EDIT_USER'
export const EDIT_USER_SUCCEED = 'EDIT_USER_SUCCEED'
export const DELETE_USER = 'DELETE_USER'
export const DELETE_USER_SUCCEED = 'DELETE_USER_SUCCEED'
export const GET_USER_BY_LOGIN = 'GET_USER_BY_LOGIN'
export const GET_USER_BY_LOGIN_SUCCEED = 'GET_USER_BY_LOGIN_SUCCEED'

