
export const GET_DOCUMENTS_BY_USER_ID = 'GET_DOCUMENTS_BY_USER_ID'
export const GET_DOCUMENTS_BY_USER_ID_SUCCEED = 'GET_DOCUMENTS_BY_USER_ID_SUCCEED'
export const UPLOAD_DOCUMENT = 'UPLOAD_DOCUMENT'
export const UPLOAD_DOCUMENT_SUCCEED = 'UPLOAD_DOCUMENT_SUCCEED'


