export const GET_DOCUMENTS_BY_USER_ID = 'GET_DOCUMENTS_BY_USER_ID'
export const GET_DOCUMENTS_BY_USER_ID_SUCCEED = 'GET_DOCUMENTS_BY_USER_ID_SUCCEED'
export const UPLOAD_DOCUMENT = 'UPLOAD_DOCUMENT'
export const UPLOAD_DOCUMENT_SUCCEED = 'UPLOAD_DOCUMENT_SUCCEED'
export const GET_DOCUMENT_TYPES = 'GET_DOCUMENT_TYPES'
export const GET_DOCUMENT_TYPES_SUCCEED = 'GET_DOCUMENT_TYPES_SUCCEED'
export const ADD_DOCUMENT_TYPE = 'ADD_DOCUMENT_TYPE'
export const ADD_DOCUMENT_TYPE_SUCCEED = 'ADD_DOCUMENT_TYPE_SUCCEED'
export const DELETE_DOCUMENT_TYPE = 'DELETE_DOCUMENT_TYPE'
export const DELETE_DOCUMENT_TYPE_SUCCEED = 'DELETE_DOCUMENT_TYPE_SUCCEED'


